### ISSUE TITLE
RFC: Can I migrate Helm to topolvm repository from helm repository?

### ISSUE THREAD

**Issue by llamerada-jp** [topolvm/helm#12]
@kfirfer @frederiko

// This message is the same as the one posted on slack.
// https://topolvm.slack.com/archives/CSXMYS3L2/p1617588995001300

We'd like to discuss topolvm's helm chart. I think it would be better to manage charts in topolvm repository than helm repository.
Currently, we provide the way to topolvm installation based on the manifests which are generated by kustomize.
Also, the manifests in CI are generated in the same way too.
However, the configuration of topolvm has got complicated day by day. The installation document has been complicated too.
So we'd change the official way to generate manifests to helm.
Then I found a problem. If chars are in helm repository, we need to update this repository
when the new configurations are added to topolvm. To avoid this problem, I considered how about moving charts to topolvm repository.
Do you have any comments or any ideas?

**Comment by llamerada-jp** [comment]
@kfirfer @frederiko
I was wondering if you could reply.

**Comment by frederiko** [comment]
Hi,

Apologies for the delay. I missed this somehow.

I agree this should be hosted in the same repo as topolvm. This was an earlier suggestion by the maintainers, and it’s been like that since earlier days.

 I would love to come back and contribute to the charts later on. I don’t know if this is as nearly as complete. Anyway, Feel free to make the arrangements and place where you think it should be.

**Comment by llamerada-jp** [comment]
@frederiko 
Thank you for your reply!

**Comment by toshipp** [comment]
@kfirfer 
I just found your deprecation notice, so I close the issue.
Thank you for your great effort and welcome your future contribution!
